spring:
  application:
    name: apigateway
  main:
    web-application-type: reactive

  cloud:
    gateway:
    discovery:
      locator:
        enabled: true
    routes:
      - id: userservice
          uri: lb://userservice
          predicates:
            - Path=/api/v1/**
      - id: webapp
          uri: lb://webapp
          predicates:
            - Path=/**
      - id: innovation
          uri: lb://innovation
          predicates:
            - Path=/api/v2/**
server:
  port: ${9000}
eureka:
  client:
    serviceURL:
      defaultZone: http://localhost:9091/eureka
    instance:
      preferIpAddress: true
  register-with-eureka: true

jwtSecretKey: "secret"
